"""
AXIOM Agent 6 — Mission Builder
Generates full starter code for today's mission.
Auto-creates a GitHub repo and pushes all files.
"""

import anthropic
import json
import requests
import base64
import os


class MissionBuilder:
    def __init__(self, anthropic_key: str, github_token: str, github_username: str):
        self.client = anthropic.Anthropic(api_key=anthropic_key)
        self.github_token = github_token
        self.github_username = github_username
        self.headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json"
        }

    def _call_claude(self, system: str, user: str) -> str:
        msg = self.client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=4000,
            system=system,
            messages=[{"role": "user", "content": user}]
        )
        return msg.content[0].text

    def _generate_project_files(self, mission_data: dict) -> dict:
        """Generate all starter files for the mission project."""
        system = """You are a senior developer creating a starter project for a student.
Generate a complete, runnable starter project.
Return ONLY a JSON object with this exact structure:
{
  "files": [
    {"path": "filename.ext", "content": "full file content here"},
    {"path": "subfolder/file.ext", "content": "content"}
  ],
  "setup_instructions": "2-3 lines on how to run this project"
}
Rules:
- Include 3-5 files maximum
- Make the code actually runnable
- Add helpful comments explaining each part
- Include a proper README.md
- Keep each file under 100 lines
Return ONLY the JSON, no markdown."""

        user = f"""Create a complete starter project for this mission:
Title: {mission_data['mission_title']}
Description: {mission_data['mission_description']}
Tech stack: {', '.join(mission_data.get('tech_stack', ['Python']))}
Difficulty: {mission_data.get('difficulty', 'beginner')}
Steps: {json.dumps(mission_data.get('starter_steps', []))}

Generate a complete, working starter project that helps the student get started immediately."""

        raw = self._call_claude(system, user)
        try:
            clean = raw.strip().replace("```json", "").replace("```", "")
            return json.loads(clean)
        except Exception as e:
            print(f"   ⚠️ JSON parse error: {e}")
            return {
                "files": [
                    {
                        "path": "main.py",
                        "content": f"# {mission_data['mission_title']}\n# Auto-generated by AXIOM\n\nprint('Hello! Start building here.')\n"
                    },
                    {
                        "path": "README.md",
                        "content": f"# {mission_data['mission_title']}\n\n{mission_data['mission_description']}\n\n## How to run\n```\npython main.py\n```\n"
                    }
                ],
                "setup_instructions": "Run: python main.py"
            }

    def _create_github_repo(self, repo_name: str, description: str) -> dict | None:
        """Create a new GitHub repo."""
        # Clean repo name
        clean_name = repo_name.lower().replace(" ", "-").replace("_", "-")
        clean_name = ''.join(c for c in clean_name if c.isalnum() or c == '-')[:50]
        clean_name = f"axiom-mission-{clean_name}"

        payload = {
            "name": clean_name,
            "description": f"🤖 Auto-generated by AXIOM | {description[:100]}",
            "private": False,
            "auto_init": False
        }

        try:
            r = requests.post(
                "https://api.github.com/user/repos",
                headers=self.headers,
                json=payload,
                timeout=15
            )
            if r.status_code == 201:
                data = r.json()
                return {"name": clean_name, "url": data["html_url"], "clone_url": data["clone_url"]}
            elif r.status_code == 422:
                # Repo might already exist, try with timestamp
                import time
                clean_name = f"{clean_name}-{int(time.time()) % 10000}"
                payload["name"] = clean_name
                r2 = requests.post("https://api.github.com/user/repos", headers=self.headers, json=payload, timeout=15)
                if r2.status_code == 201:
                    data = r2.json()
                    return {"name": clean_name, "url": data["html_url"], "clone_url": data["clone_url"]}
            print(f"   ⚠️ Repo creation failed: {r.status_code} {r.text[:100]}")
            return None
        except Exception as e:
            print(f"   ⚠️ Repo creation error: {e}")
            return None

    def _push_files(self, repo_name: str, files: list) -> bool:
        """Push all generated files to the GitHub repo."""
        success_count = 0
        for file in files:
            path = file.get("path", "main.py")
            content = file.get("content", "")
            encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")

            payload = {
                "message": f"🤖 AXIOM: Add {path}",
                "content": encoded
            }

            try:
                r = requests.put(
                    f"https://api.github.com/repos/{self.github_username}/{repo_name}/contents/{path}",
                    headers=self.headers,
                    json=payload,
                    timeout=15
                )
                if r.status_code in [200, 201]:
                    success_count += 1
                else:
                    print(f"   ⚠️ Failed to push {path}: {r.status_code}")
            except Exception as e:
                print(f"   ⚠️ Push error for {path}: {e}")

        return success_count > 0

    def _generate_dashboard_data(self, github_data: dict, roast_data: dict,
                                  trend_data: dict, mission_data: dict, repo_info: dict) -> dict:
        """Generate JSON data for the live dashboard."""
        from datetime import datetime
        return {
            "last_run": datetime.now().strftime("%d %b %Y, %I:%M %p"),
            "github": {
                "username": github_data["username"],
                "score": github_data["profile_score"],
                "repos": github_data["total_repos"],
                "stars": github_data["total_stars"],
                "streak": github_data["commit_streak_days"],
                "languages": github_data["languages"],
                "weak_spots": github_data["weak_spots"][:2]
            },
            "roast": roast_data.get("roast", "")[:300],
            "fixes": roast_data.get("fixes", [])[:3],
            "interview_questions": roast_data.get("interview_questions", []),
            "trending": trend_data.get("trending", [])[:3],
            "missing_skills": trend_data.get("missing_skills", []),
            "market_insight": trend_data.get("market_insight", ""),
            "mission": {
                "title": mission_data.get("mission_title", ""),
                "description": mission_data.get("mission_description", ""),
                "tech_stack": mission_data.get("tech_stack", []),
                "difficulty": mission_data.get("difficulty", "beginner"),
                "hours": mission_data.get("estimated_hours", 5),
                "why": mission_data.get("why_hireable", ""),
                "steps": mission_data.get("starter_steps", [])
            },
            "repo": repo_info
        }

    def run(self, github_data: dict, roast_data: dict,
            trend_data: dict, mission_data: dict) -> dict:

        print("   🔨 Generating starter code with Claude...")
        project = self._generate_project_files(mission_data)
        files = project.get("files", [])
        setup = project.get("setup_instructions", "")
        print(f"   ✅ Generated {len(files)} files")

        print("   📦 Creating GitHub repo...")
        repo_info = self._create_github_repo(
            mission_data.get("mission_title", "mission"),
            mission_data.get("mission_description", "")
        )

        if repo_info:
            print(f"   ✅ Repo created: {repo_info['url']}")
            print("   📤 Pushing files to GitHub...")
            pushed = self._push_files(repo_info["name"], files)
            if pushed:
                print(f"   ✅ All files pushed to {repo_info['url']}")
        else:
            print("   ⚠️ Could not create repo — files generated but not pushed")
            repo_info = {"url": "", "name": ""}

        # Generate dashboard data
        dashboard_data = self._generate_dashboard_data(
            github_data, roast_data, trend_data, mission_data, repo_info
        )

        return {
            "files": files,
            "setup_instructions": setup,
            "repo_info": repo_info,
            "dashboard_data": dashboard_data,
            "file_count": len(files)
        }